--Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore all columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--Explore all countries our customers came from
SELECT DISTINCT
country
FROM DataWarehouse_Portfolio1..dim_customers


--Find the date of the first and last order
SELECT
MIN(order_date) AS first_order, 
MAX(order_date) AS Last_order
FROM DataWarehouse_Portfolio1..fact_sales

-- Find the numbers of years customers ordered for products
SELECT 
DATEDIFF(year,MIN(order_date), MAX(order_date)) AS order_range_years
-- SELECT DATEDIFF(months,MIN(order_date), MAX(order_date)) AS order_range_month
FROM DataWarehouse_Portfolio1..fact_sales

-- Find the youngest and oldest customers
SELECT
MIN(birthdate) AS youngest_customer, 
DATEDIFF(year,MIN(birthdate), GETDATE()) AS Youngest_age,
MAX(birthdate) AS oldest_customer,
DATEDIFF(year,MAX(birthdate), GETDATE()) AS Oldest_age
FROM DataWarehouse_Portfolio1..dim_customers




-- Find the total sales
SELECT
SUM(sales_amount) AS Total_sales
FROM DataWarehouse_Portfolio1..fact_sales

-- Find how many items sold
SELECT
SUM(quantity) AS Total_Quantity
FROM DataWarehouse_Portfolio1..fact_sales

--Find The Average Selling Price
SELECT
AVG(price) AS Average_Price
FROM DataWarehouse_Portfolio1..fact_sales

-- Find the total number of orders
SELECT
COUNT(order_number) AS Total_orders,
COUNT(DISTINCT order_number) AS Total0rders_Without_Duplicates     --  Removing duplicates from the count
FROM DataWarehouse_Portfolio1..fact_sales

--Find the total number of products
SELECT
COUNT(product_key) AS Total_Products,
COUNT(DISTINCT product_key) AS Total_Products_Without_Duplicates     --  Removing duplicates from the count
FROM DataWarehouse_Portfolio1..dim_products


--Find the total numbers of Customers
SELECT
COUNT(DISTINCT customer_key) AS Total_customers
FROM DataWarehouse_Portfolio1..dim_customers

--Find the total customers that placed an order
SELECT
COUNT(DISTINCT customer_key) AS Customers_that_placed_Order
FROM DataWarehouse_Portfolio1..fact_sales



--GENERATE A REPORT THAT SHOWS ALL KEY METRICS
SELECT 'Total sales' AS Measure_name,SUM(sales_amount) AS Measure_value
FROM DataWarehouse_Portfolio1..fact_sales
UNION ALL 
SELECT 'Total Quantity' , SUM(quantity) FROM DataWarehouse_Portfolio1..fact_sales 
UNION ALL
SELECT 'Average Price', AVG(price) FROM DataWarehouse_Portfolio1..fact_sales
UNION ALL
SELECT 'Total No. of orders', COUNT(DISTINCT order_number) FROM DataWarehouse_Portfolio1..fact_sales
UNION ALL
SELECT 'Total No. of Products', COUNT(DISTINCT product_key) FROM DataWarehouse_Portfolio1..dim_products
UNION ALL
SELECT 'Total No. of Customers', COUNT(DISTINCT customer_key) FROM DataWarehouse_Portfolio1..fact_sales


-- Find Total Customers By Countries
SELECT 
Country,
COUNT(DISTINCT customer_key) AS Total_customers
FROM DataWarehouse_Portfolio1..dim_customers
GROUP BY Country 
ORDER BY Total_customers DESC

-- Find Total customers by Gender
SELECT 
gender,
COUNT(DISTINCT customer_key) AS Total_customers
FROM DataWarehouse_Portfolio1..dim_customers
GROUP BY gender 
ORDER BY Total_customers DESC

-- What is the total Revenue generated by each customers
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS Total_Revenue  
FROM DataWarehouse_Portfolio1..fact_sales f
LEFT JOIN DataWarehouse_Portfolio1..dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Revenue DESC

-- What is the distribution of sold items across countries
SELECT
c.country,
SUM(f.quantity) AS Total_items_sold
FROM DataWarehouse_Portfolio1..fact_sales f
LEFT JOIN DataWarehouse_Portfolio1..dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY Total_items_sold DESC


--Top 5 Products that Generates the Highest Revenue
SELECT TOP 5
p.product_key,
SUM(f.sales_amount) AS Total_Revenue
--ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS Rank_products
FROM DataWarehouse_Portfolio1..fact_sales f
LEFT JOIN DataWarehouse_Portfolio1..dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_key
ORDER BY Total_Revenue DESC

-- The 5 Worst Performing Products in terms of sales
SELECT TOP 5
p.product_key,
SUM(f.sales_amount) AS Total_sales
FROM DataWarehouse_Portfolio1..fact_sales f
LEFT JOIN DataWarehouse_Portfolio1..dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_key
ORDER BY Total_sales ASC

-- The 5 customers with fewest orders placed
SELECT TOP 5
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS Total_Order 
FROM DataWarehouse_Portfolio1..fact_sales f
LEFT JOIN DataWarehouse_Portfolio1..dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Order ASC


